import React from "react";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import {
  Flex,
  Text,
  Box,
  Container,
  Stack,
  useColorModeValue,
} from "@chakra-ui/react";
import Nav from "./Nav";

const Layout = ({ children, title = "Simple To Do" }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <Flex
        minH={"88vh"}
        align={"center"}
        justify={"center"}
        bg={useColorModeValue("gray.50", "gray.800")}
      >
        <main className={styles.main}>{children}</main>
      </Flex>
      <footer>
        <Flex
          minH={"5vh"}
          align={"center"}
          justify={"center"}
          bg={useColorModeValue("gray.50", "gray.800")}
        >
          <span className={styles.logo}>
            <Image src='/logo.svg' alt='Vercel Logo' width={20} height={20} />
          </span>
          <Text ml={3} mb={1.5}>
            Kits Create All rights reserved
          </Text>
        </Flex>
      </footer>
    </div>
  );
};

export default Layout;
