import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRecoilValue, useRecoilState } from "recoil";
import { todoState, filterState } from "../components/atom";
import Filter from "../components/Filter";
import { TODO } from "../components/types";

const Home: NextPage = () => {
  const [todos, setTodos] = useRecoilState(todoState);
  const filter = useRecoilValue(filterState);

  const filterTodo = (tds: TODO[]): TODO[] => {
    if (filter === "all") return tds;
    const filtered = tds.filter((td) => td.status === filter);
    return filtered;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>To-Do-List</h1>
        <code className={styles.code}>pages/index.tsx</code>

        <span>フィルター</span>
        <Filter />

        <ul>
          {filterTodo(todos).map((todo) => (
            <li key={todo.id}>
              <span>{todo.title}</span>
              <select></select>
            </li>
          ))}
        </ul>

        <p className={styles.description}>Get started by editing </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
